dist: trusty
language: python
python:
- '3.6'
install: "pip install -r requirements.txt"
jobs:
  include:
  - stage: Self-test topology tool
    script:
    - cd $TRAVIS_BUILD_DIR/selftest/tool_tests && pytest test_topology.py && cd $TRAVIS_BUILD_DIR/
